apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-executor-cluster-role
rules:
- apiGroups: [""]
  verbs: ["create", "get", "watch", "list"]
  resources: ["pods/exec", "pods", "pods/log"]
