apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-executor-cluster-role
rules:
- apiGroups: [""]
  verbs: ["exec", "get", "watch", "list"]
  resources: ["pods", "pods/log"]
