apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "dev" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: pod-executor-cluster-role-binding
subjects:
- kind: User
  name: pod-executor # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pod-executor-cluster-role
  apiGroup: rbac.authorization.k8s.io
