replicaCount: 1
image:
  repository: docker.io/yuvarajengineer/gateway
  tag: main
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 8080
ingress:
  enabled: true
  hostname: "*.amazonaws.com"
resources: {}
