targetSystem: "linux"
datadog:
  apiKeyExistingSecret: "datadog-secret"
  clusterName: chaos-cluster
  site: "datadoghq.com"
  tags:
    - env: prod
  apm:
    instrumentation:
      enabled: true
      language_detection:
        enabled: true
      libVersions:
         java: "1"
    useSocketVolume: false
    socketPath: /var/run/datadog/apm.socket
    hostSocketPath: /var/run/datadog/
    portEnabled: false
    socketEnabled: true
    enabled: true
    port: 8126

  logs:
    containerCollectAll: false
    enabled: false
  processAgent:
    processCollection: true
  orchestratorExplorer:
    enabled: true
  dogstatsd:
    useHostPort: true
  kubelet:
    tlsVerify: false
  networkMonitoring:
    enabled: true
  securityAgent:
    runtime:
      enabled: false
    compliance:
      enabled: false
  agents:
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
  clusterAgent:
    enabled: true
    admissionController:
      enabled: true
      mutateUnlabelled: true
  
