datadog:
  clusterName: chaos-cluster
  apiKeyExistingSecret: "datadog-secret"
  site: datadoghq.com
  apm:
    portEnabled: true
    socketEnabled: false 
  logs:
    enabled: false
    containerCollectAll: false
  processAgent:
    processCollection: true
  dogstatsd:
    useHostPort: true
  kubelet:
    tlsVerify: false
  networkMonitoring:
    enabled: true
  securityAgent:
    compliance:
      enabled: false
    runtime:
      enabled: false
agents:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
clusterAgent:
  enabled: true
  admissionController:
    enabled: true
    mutateUnlabelled: true
