nameOverride:  
fullnameOverride:  
targetSystem: "linux"
commonLabels: {}
registry:  
datadog:
  apiKeyExistingSecret: "datadog-secret"
  clusterName: chaos-cluster
  secretAnnotations: {}
  secretBackend:
    command:  
    arguments:  
    timeout:  
    enableGlobalPermissions: true
    roles: []
  securityContext:
    runAsUser: 0
  hostVolumeMountPropagation: None
  site: "datadoghq.com"
  dd_url:  
  logLevel: INFO
  kubeStateMetricsEnabled: false
  kubeStateMetricsNetworkPolicy:
    create: false
  kubeStateMetricsCore:
    enabled: true
    rbac:
      create: true
    ignoreLegacyKSMCheck: true
    collectSecretMetrics: true
    collectConfigMaps: true
    collectVpaMetrics: false
    collectCrdMetrics: false
    collectApiServicesMetrics: false
    useClusterCheckRunners: false
    labelsAsTags: {}
    annotationsAsTags: {}
  clusterChecks:
    enabled: true
    shareProcessNamespace: false
  nodeLabelsAsTags: {}
  podLabelsAsTags: {}
  podAnnotationsAsTags: {}
  namespaceLabelsAsTags: {}
  namespaceAnnotationsAsTags: {}
  kubernetesResourcesLabelsAsTags: {}
  kubernetesResourcesAnnotationsAsTags: {}
  originDetectionUnified:
    enabled: false
  tags: []
  checksCardinality:  
  kubelet:
    host:
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    tlsVerify:  
    hostCAPath:
    agentCAPath:
    podLogsPath:
    coreCheckEnabled: true
    podResourcesSocketDir: /var/lib/kubelet/pod-resources
  expvarPort: 6000
  dogstatsd:
    port: 8125
    originDetection: false
    tags: []
    tagCardinality: low
    useSocketVolume: true
    socketPath: /var/run/datadog/dsd.socket
    hostSocketPath: /var/run/datadog/
    useHostPort: false
    useHostPID: false
    nonLocalTraffic: true
  useHostPID: true
  collectEvents: true
  kubernetesUseEndpointSlices: false
  kubernetesEvents:
    sourceDetectionEnabled: false
    filteringEnabled: false
    unbundleEvents: false
    collectedEventTypes:
      - kind: Pod
        reasons:
          - Failed
          - BackOff
          - Unhealthy
          - FailedScheduling
          - FailedMount
          - FailedAttachVolume
      - kind: Node
        reasons:
          - TerminatingEvictedPod
          - NodeNotReady
          - Rebooted
          - HostPortConflict
      - kind: CronJob
        reasons:
          - SawCompletedJob
  clusterTagger:
    collectKubernetesTags: false
  leaderElection: true
  leaderLeaseDuration:  
  leaderElectionResource: configmap
  remoteConfiguration:
    enabled: true
  logs:
    enabled: false
    containerCollectAll: false
    containerCollectUsingFiles: true
    autoMultiLineDetection: false
  apm:
    socketEnabled: true
    portEnabled: true
    useLocalService: false
    enabled: false
    port: 8126
    useSocketVolume: false
    socketPath: /var/run/datadog/apm.socket
    hostSocketPath: /var/run/datadog/
    errorTrackingStandalone:
      enabled: false
    instrumentation:
      enabled: false
      enabledNamespaces: []
      disabledNamespaces: []
      libVersions: {}
      targets: []
      skipKPITelemetry: false
      language_detection:
        enabled: true
      injector:
        imageTag: ""
  asm:
    threats:
      enabled: false
    sca:
      enabled: false
    iast:
      enabled: false
  otlp:
    receiver:
      protocols:
        grpc:
          enabled: false
          endpoint: "0.0.0.0:4317"
          useHostPort: true
        http:
          enabled: false
          endpoint: "0.0.0.0:4318"
          useHostPort: true
    logs:
      enabled: false
  otelCollector:
    enabled: false
    ports:
      - containerPort: "4317"
        name: otel-grpc
      - containerPort: "4318"
        name: otel-http
    config: null
    featureGates: null
    rbac:
      create: true
      rules: []
    logs:
      enabled: false
  profiling:
    enabled: null
  envFrom: []
  env: []
  envDict: {}
  confd: {}
  checksd: {}
  dockerSocketPath:  
  criSocketPath:  
  containerRuntimeSupport:
    enabled: true
  processAgent:
    enabled: true
    processCollection: false
    stripProcessArguments: false
    processDiscovery: true
    runInCoreAgent: true
    containerCollection: true
  disableDefaultOsReleasePaths: false
  disablePasswdMount: false
  osReleasePath: /etc/os-release
  systemProbe:
    debugPort: 0
    enableConntrack: true
    seccomp: localhost/system-probe
    seccompRoot: /var/lib/kubelet/seccomp
    bpfDebug: false
    apparmor: unconfined
    enableTCPQueueLength: false
    enableOOMKill: false
    mountPackageManagementDirs: []
    runtimeCompilationAssetDir: /var/tmp/datadog-agent/system-probe
    btfPath: ""
    collectDNSStats: true
    maxTrackedConnections: 131072
    conntrackMaxStateSize: 131072  
    conntrackInitTimeout: 10s
    enableDefaultOsReleasePaths: true
    enableDefaultKernelHeadersPaths: true
  containerImageCollection:
    enabled: true
  orchestratorExplorer:
    enabled: true
    container_scrubbing:
      enabled: true
    customResources: []
  helmCheck:
    enabled: false
    collectEvents: false
    valuesAsTags: {}
  networkMonitoring:
    enabled: false
  serviceMonitoring:
    enabled: false
    httpMonitoringEnabled:
    http2MonitoringEnabled:
    tls:
      go:
        enabled:
      istio:
        enabled:
      nodejs:
        enabled:
      native:
        enabled:
  traceroute:
    enabled: false
  discovery:
    enabled:  
    networkStats:
      enabled: true
  gpuMonitoring:
    enabled: false
    configureCgroupPerms: false
    runtimeClassName: "nvidia"
  sbom:
    containerImage:
      enabled: false
      uncompressedLayersSupport: true
      overlayFSDirectScan: false
    host:
      enabled: false
  securityAgent:
    compliance:
      enabled: false
      configMap:
      checkInterval: 20m
      xccdf:
        enabled: false
      host_benchmarks:
        enabled: true
    runtime:
      enabled: false
      fimEnabled: false
      useSecruntimeTrack: true
      policies:
        configMap:
      syscallMonitor:
        enabled: false
      network:
        enabled: true
      activityDump:
        enabled: true
        tracedCgroupsCount: 3
        cgroupDumpTimeout: 20
        cgroupWaitListSize: 0
        pathMerge:
          enabled: false
      securityProfile:
        enabled: true
        anomalyDetection:
          enabled: true
        autoSuppression:
          enabled: true
  networkPolicy:
    create: false
    flavor: kubernetes
    cilium:
      dnsSelector:
        toEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": kube-system
              "k8s:k8s-app": kube-dns
  prometheusScrape:
    enabled: false
    serviceEndpoints: false
    additionalConfigs: []
    version: 2
  ignoreAutoConfig: []
  containerExclude:  
  containerInclude:
  containerExcludeLogs:
  containerIncludeLogs:
  containerExcludeMetrics:
  containerIncludeMetrics:
  excludePauseContainer: true
  containerLifecycle:
    enabled: true
clusterAgent:
  enabled: true
  shareProcessNamespace: false
  image:
    name: cluster-agent
    tag: 7.63.3
    digest: ""
    repository:
    pullPolicy: IfNotPresent
    pullSecrets: []
    doNotCheckTag:  
  securityContext: {}
  containers:
    clusterAgent:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
    initContainers:
      securityContext: {}
      resources: {}
  command: []
  token: ""
  tokenExistingSecret: ""
  replicas: 1
  revisionHistoryLimit: 10
  rbac:
    create: true
    flareAdditionalPermissions: true
    serviceAccountName: default
    serviceAccountAnnotations: {}
    serviceAccountAdditionalLabels: {}
    automountServiceAccountToken: true
  podSecurity:
    podSecurityPolicy:
      create: false
    securityContextConstraints:
      create: false
  metricsProvider:
    enabled: false
    registerAPIService: true
    wpaController: false
    useDatadogMetrics: false
    createReaderRbac: true
    aggregator: avg
    service:
      type: ClusterIP
      port: 8443
    endpoint:  
  env: []
  envFrom: []
  envDict: {}
  admissionController:
    enabled: true
    validation:
      enabled: true
    mutation:
      enabled: true
    webhookName: datadog-webhook
    mutateUnlabelled: false
    configMode:  
    failurePolicy: Ignore
    containerRegistry:
    remoteInstrumentation:
      enabled: false
    port: 8000
    cwsInstrumentation:
      enabled: false
      mode: remote_copy
    kubernetesAdmissionEvents:
      enabled: false
    agentSidecarInjection:
      enabled: false
      provider:
      clusterAgentCommunicationEnabled: true
      containerRegistry:
      imageName:
      imageTag:
      selectors: []
      profiles: []
  confd: {}
  advancedConfd: {}
  kubernetesApiserverCheck:
    disableUseComponentStatus: false
  resources: {}
  priorityClassName:  
  nodeSelector: {}
  tolerations: []
  affinity: {}
  topologySpreadConstraints: []
  healthPort: 5556
  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 15
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 6
  readinessProbe:
    initialDelaySeconds: 15
    periodSeconds: 15
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 6
  startupProbe:
    initialDelaySeconds: 15
    periodSeconds: 15
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  deploymentAnnotations: {}
  podAnnotations: {}
  useHostNetwork: false
  dnsConfig: {}
  volumes: []
  volumeMounts: []
  datadog_cluster_yaml: {}
  createPodDisruptionBudget: false
  networkPolicy:
    create: false
  additionalLabels: {}
  containerExclude:  
  containerInclude:
existingClusterAgent:
  join: false
  tokenSecretName:  
  serviceName:  
  clusterchecksEnabled: true
fips:
  enabled: false
  port: 9803
  portRange: 15
  use_https: false
  resources: {}
  local_address: "127.0.0.1"
  image:
    name: fips-proxy
    tag: 1.1.8
    pullPolicy: IfNotPresent
    digest: ""
    repository:
  customFipsConfig: {}  
agents:
  enabled: true
  shareProcessNamespace: false
  revisionHistoryLimit: 10
  image:
    name: agent
    tag: 7.63.3
    digest: ""
    tagSuffix: ""
    repository:
    doNotCheckTag:  
    pullPolicy: IfNotPresent
    pullSecrets: []
  rbac:
    create: true
    serviceAccountName: default
    serviceAccountAnnotations: {}
    serviceAccountAdditionalLabels: {}
    automountServiceAccountToken: true
  podSecurity:
    podSecurityPolicy:
      create: false
    securityContextConstraints:
      create: false
    seLinuxContext:
      rule: MustRunAs
      seLinuxOptions:
        user: system_u
        role: system_r
        type: spc_t
        level: s0
    privileged: false
    capabilities:
      - SYS_ADMIN
      - SYS_RESOURCE
      - SYS_PTRACE
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
      - IPC_LOCK
      - CHOWN
      - AUDIT_CONTROL
      - AUDIT_READ
      - DAC_READ_SEARCH
    allowedUnsafeSysctls: []
    volumes:
      - configMap
      - downwardAPI
      - emptyDir
      - hostPath
      - secret
    seccompProfiles:
      - "runtime/default"
      - "localhost/system-probe"
    apparmor:
      enabled: true
    apparmorProfiles:
      - "runtime/default"
      - "unconfined"
    defaultApparmor: runtime/default
  containers:
    agent:
      env: []
      envFrom: []
      envDict: {}
      logLevel:  
      resources: {}
      healthPort: 5555
      livenessProbe:
        initialDelaySeconds: 15
        periodSeconds: 15
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 6
      readinessProbe:
        initialDelaySeconds: 15
        periodSeconds: 15
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 6
      startupProbe:
        initialDelaySeconds: 15
        periodSeconds: 15
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 6
      securityContext: {}
      ports: []
    processAgent:
      env: []
      envFrom: []
      envDict: {}
      logLevel:  
      resources: {}
      securityContext: {}
      ports: []
    otelAgent:
      env: []
      envFrom: []
      envDict: {}
      resources: {}
      securityContext: {}
      ports: []
      volumeMounts: []
    traceAgent:
      env: []
      envFrom: []
      envDict: {}
      logLevel:  
      resources: {}
      livenessProbe:
        initialDelaySeconds: 15
        periodSeconds: 15
        timeoutSeconds: 5
      securityContext: {}
      ports: []
    systemProbe:
      env: []
      envFrom: []
      envDict: {}
      logLevel:  
      resources: {}
      securityContext:
        privileged: false
        capabilities:
          add: ["SYS_ADMIN", "SYS_RESOURCE", "SYS_PTRACE", "NET_ADMIN", "NET_BROADCAST", "NET_RAW", "IPC_LOCK", "CHOWN", "DAC_READ_SEARCH"]
      ports: []
    securityAgent:
      env: []
      envFrom: []
      envDict: {}
      logLevel:  
      resources: {}
      ports: []
    initContainers:
      resources: {}
      securityContext: {}
      volumeMounts: []
  volumes: []
  volumeMounts: []
  useHostNetwork: false
  dnsConfig: {}
  daemonsetAnnotations: {}
  podAnnotations: {}
  tolerations: []
  nodeSelector: {}
  affinity: {}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "10%"
  priorityClassCreate: false
  priorityClassName:
  priorityPreemptionPolicyValue: PreemptLowerPriority
  priorityClassValue: 1000000000
  podLabels: {}
  additionalLabels: {}
  useConfigMap:  
  customAgentConfig: {}
  networkPolicy:
    create: false
  localService:
    overrideName: ""
    forceLocalServiceEnabled: false
clusterChecksRunner:
  enabled: false
  image:
    name: agent
    tag: 7.63.3
    digest: ""
    tagSuffix: ""
    repository:
    pullPolicy: IfNotPresent
    pullSecrets: []
  createPodDisruptionBudget: false
  rbac:
    create: true
    dedicated: false
    serviceAccountAnnotations: {}
    serviceAccountAdditionalLabels: {}
    automountServiceAccountToken: true
    serviceAccountName: default
  replicas: 2
  revisionHistoryLimit: 10
  resources: {}
  affinity: {}
  topologySpreadConstraints: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  dnsConfig: {}
  priorityClassName:  
  nodeSelector: {}
  tolerations: []
  healthPort: 5557
  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 15
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 6
  readinessProbe:
    initialDelaySeconds: 15
    periodSeconds: 15
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 6
  startupProbe:
    initialDelaySeconds: 15
    periodSeconds: 15
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 6
  deploymentAnnotations: {}
  podAnnotations: {}
  env: []
  envFrom: []
  envDict: {}
  volumes: []
  volumeMounts: []
  networkPolicy:
    create: false
  additionalLabels: {}
  securityContext: {}
  containers:
    agent:
      securityContext: {}
    initContainers:
      securityContext: {}
  ports: []
datadog-crds:
  crds:
    datadogMetrics: true
    datadogPodAutoscalers: true
kube-state-metrics:
  image:
    repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
  rbac:
    create: true
  serviceAccount:
    create: true
    name:
  resources: {}
  nodeSelector:
    kubernetes.io/os: linux
providers:
  gke:
    autopilot: false
    cos: false
    gdc: false
  eks:
    ec2:
      useHostnameFromFile: false
  aks:
    enabled: false
  talos:
    enabled: false
remoteConfiguration:
  enabled: true
