registry: "public.ecr.aws/datadog"
datadog:
  clusterName: chaos-cluster
  apiKeyExistingSecret: "datadog-secret"
  site: "datadoghq.com"
  tags:
    - "env:prod"
  apm:
    portEnabled: true
clusterAgent:
  admissionController:
    enabled: true
    configMode: service
