apiVersion: batch/v1
kind: Job
metadata:
  name: init-mysql-db
spec:
  template:
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: db-init-config
      containers:
      - name: init-db
        image: docker.io/yuvarajengineer/batchuser:main
        volumeMounts:
          - name: config-volume
            mountPath: /config
        env:
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_HOST
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: db-init-config
              key: MYSQL_PORT
      restartPolicy: Never
  backoffLimit: 2
