apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    tags.datadoghq.com/env: "prod"
    tags.datadoghq.com/service: "user-service"
    tags.datadoghq.com/version: "1.0"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      annotations:
        admission.datadoghq.com/java-lib.version: "v1.31.2"
      labels:
        admission.datadoghq.com/enabled: "true"
        app: {{ .Chart.Name }}
        tags.datadoghq.com/env: "prod"
        tags.datadoghq.com/service: "user-service"
        tags.datadoghq.com/version: "1.0"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: DD_AGENT_HOST
          value: datadog.datadog.svc.cluster.local
        ports:
        - containerPort: {{ .Values.service.port }}
        livenessProbe:
          httpGet:
            path: /manage/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /manage/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /manage/health
            port: 8081
          failureThreshold: 30
          initialDelaySeconds: 30
          periodSeconds: 5
        securityContext:
          readOnlyRootFilesystem: false
       
