name: Destroy k8s resources
on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-k8s-destroy-resources]
    
jobs:
  k8s-cleanup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./k8s-cleanup
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy Applications
      run: |
        # Install Kubectl
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        kubectl version --client

        aws eks update-kubeconfig --region us-east-1 --name chaos-cluster
        kubectl delete ns dd
        kubectl delete ns app
        sleep 30
